project:
  type: book

book:
  title: "Data Visualization for Data Science"
  author: "Junjun Yin"
  date: "01/01/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - file: weekly/module_week_1_getting_started.qmd
      text: "Getting Started"
    - file: weekly/module_week_2_language_of_graphs.qmd
      text: "Language of Graphs"
    - file: weekly/module_week_3_distributions_variation.qmd
      text: "Distributions and Variations"
    - summary.qmd
    - references.qmd
    - file: syllabus.qmd
      text: "Syllabus"


bibliography: references.bib

format: 
  live-html:
    toc: true
    grid:
      sidebar-width: 280px

##  html:
##    theme:
##      - cosmo
##      - brand
##    csss: styles.css
##    toc: true

  # pdf:
  #   documentclass: scrreprt

# filters:
#   - r-wasm/live



