# Introduction {.unnumbered}
Welcome to Data Visualiztion for Data Science (DATS 2102)

## Weekly Modules
* `Week 1` - [Getting Started](weekly/module_week_1_getting_started.qmd)
* `Week 2` - [Language of Graphs](weekly/module_week_2_language_of_graphs.qmd)
* `Week 3` - [Distributions and Variations](weekly/module_week_3_distributions_variation.qmd)
* `Week 4` - [Wrangling with Pandas](weekly/module_week_4_wrangling_with_pandas.qmd)
* `Week 5` - [Perception and Principles](weekly/module_week_5_perception_principles.qmd)
* `Week 6` - [Comparisons](weekly/module_week_6_comparisons.qmd)
* `Mid-term` - [Mid-term Project](weekly/mid_term_project_module_page.qmd)
* `Week 7` - [Text, Labels, and Tables](weekly/module_week_7_text_labels_tables.qmd)
* `Week 8` - [Mapping I & II](weekly/module_week_8_mapping_i_ii.qmd)
* `Week 9` - [Color & Accessibility](weekly/module_week_9_color_accessibility.qmd)
* `Week 10` - [Relationships & Modeling](weekly/module_week_10_relationships_modeling.qmd)
* `Week 11` - [Uncertainty & Error Visualization](weekly/module_week_11_uncertainty_error_visualization.qmd)
* `Week 12` - [Visualization for ML/NLP](weekly/module_week_12_viz_ml_nlp.qmd)
* `Finals` - [Final Project](weekly/final_project_module_page.qmd)

## Data Sources
* Please find useful and recommended data sources from the [data sources page](data/data_sources_module.md)